### PR TITLE
Bugfix request body

### PR DESCRIPTION
**Pull request by z-vr**

### CODE REVIEW

**Comment by assaf** [comment]
Where's the bug?

**Comment by z-vr** [comment]
@assaf The `request.body` is null after it's been consumed. see https://github.com/assaf/zombie/issues/945

**Comment by assaf** [comment]
There's no `request.body`. [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) has all the same methods as `Body`, but there's no property called `body`.

Use [clone](https://developer.mozilla.org/en-US/docs/Web/API/Request/clone) if you need to consume the body more than once.

**Comment by z-vr** [comment]
Why does it have the body property https://github.com/assaf/zombie/blob/master/src/pipeline.js#L204? Also if it inherits from Body, shouldn't it wrap the clone method behind the scenes and return values as expected: 
Body.arrayBuffer() -> Request.arrayBuffer()
Body.blob() -> Request.blob()
Body.formData() -> Request.formData()
Body.json() -> Request.json()
Body.text() -> Request.text()

**Comment by z-vr** [comment]
@assaf there's no body in the [Response] (https://developer.mozilla.org/en-US/docs/Web/API/Response) strictly speaking, but it is possible to read it in Zombie? Despite that I do see where you're coming from. Although in my opinion browser's internals should not aim to match those standards but rather meet developers' needs shouldn't they? Why not extend Request/Response to include bodies, because I think it is a common use case. Please tell me what you think.

**Comment by assaf** [comment]
Request/Response are part of the Fetch API, a feature that should be available in all modern browsers. The way they're used by Service Workers is similar in concept to the pipeline. So it's an API that exists, gaining wide spread adoption, and people are getting comfortable using it. I'd rather not invent a one-off API just for pipeline because it's actually not a common use case.

**Comment by z-vr** [comment]
How is it not a common use case when request and response bodies are needed to be checked all the time in proper web application testing? I don't understand why from browser's developer point of view it's better to make lives harder by not exposing this bodies once they are consumed? I agree for the Web APIs of `document` element there should not be the body since it's not the standard, but in the browser as a software which makes requests and receives responses, there definitely should be way to read those without so much hustle as cloning objects. So are you going to remove .body property of the response then since it's not in the docs?

**Comment by assaf** [comment]
Zombie is designed for browser testing: you're looking at whether the browser loaded a document or modified it after a successful AJAX request. It's not designed for testing HTTP traffic, there are other Node tools that do that (e.g. we used nock and node-replay).

The `body` property is not part of the public API, it's an implementation detail. If you find it offensive, you're welcome to submit a PR that changes the implementation to not use it.

**Comment by z-vr** [comment]
See I have a web application and I've develop a method for testing whether it works properly:

0. Create a pipeline handler, visit a page and invoke one of methods of my app
1. Check whether HTTP request has been made
2. In certain cases, check whether certain data is present in the request (<- problem)
3. Check for response status code
4. Check that the data in the response is correct
5. Test the JS logic, such as storing the data from the response in a variable. 

Zombie is indeed very good for browser testing, and I love it and I am very grateful! But although it is designed to test the state of the document as you say, it works as a *browser* so I really don't get why we can't have more direct access to the internals such as looking at the traffic -- we have a pipeline and it makes Zombie even more powerful and it is what distinguishes it from JSDOM which merely allows to manipulate DOM. In my opinion, it would be great to have **browser API** which allows to have a full view of what's going on behind the scenes and at the same time a **public API** for documents loaded *inside* the browser. Do I make any sense? Thank you @assaf

**Comment by assaf** [comment]
This is indeed a good use case for the pipeline. But the pipeline is not an API for instrumenting request/response and it never will be. What a pipeline does is ofter you a way to plug additional functionality, like an API for instrumenting request/response, into the browser's request/response stream. That way, every time the browser makes a request/receives a response, your code knows about it.

Your code can then present these request/response data using whatever API you choose to use. You can write your own, you can use the Node Request/Response API, you can even subclass Zombie's API and add a `body` property and cache the body there.

The one place where you must use the Fetch API is the piece of code that plugs your implementation into the pipeline.

**Comment by z-vr** [comment]
Ok cool I see thanks, but the `request.body` is already consumed by the time it reaches a pipeline handler, so I can't even clone the request! :(

**Comment by assaf** [comment]
The request body isn't consumed until `makeHTTPRequest`. If you add a request handler, it will execute before `makeHTTPRequest`, which gives you access to the request before it's sent (but after URL/headers have been fixed from the original browser request).

**Pull request closed without merging**
