### PR TITLE
Fix #927 - document .wait

### LINKED ISSUE #927: Documentation for browser.wait()
I'm attempting to simply fetch the value of a certain property on the window object after it's set. I found reference in a couple stackoverflow posts to a `browser.wait()` function that I may be able to use. This function definitely exists, but I can't find any documentation on it at all. 

Am I missing something?

### PR DESCRIPTION
**Pull request by kbariotis**
Indeed, `wait` function is a neat one especially when messing with a lot of AJAX requests in your SUT. It should be present in the docs. We can also add some examples if you would like.

### CODE REVIEW

**Comment by assaf** [comment]
Sweet. Can you add something about promises, though? This method (like most others), either called with a callback, or returns a promise you have to wait on.

**Comment by kbariotis** [comment]
@assaf looks good?

**Comment by assaf** [comment]
> options (required): Options that determine how long to wait (see below)

It can't be both optional and required

**Comment by kbariotis** [comment]
@assaf (sorry, that moment when you're trying to help and you're doing it worst!) updated and also clean up history.

Thank you

**Pull request closed without merging**
