### PR TITLE
Jsdom 6.5.1 (replaced by PR #990)

### PR DESCRIPTION
**Pull request by vcarel**
This is an upgrade of jsdom from 5.3.0 to 6.5.1, related to the issue #939.

It brings 1 breaking change:
- Element.setAttribute now expects two arguments, even for setting properties (such as "checked", "disabled"...): https://developer.mozilla.org/fr/docs/Web/API/Element/setAttribute

### CODE REVIEW

**Comment by vcarel** [comment]
ah. this is red because of a linting issue in a test file.
FYI this is not reported by `npm lint`

@assaf do you mind fixing the typo or do you want me to prepare another pull request ?

**Comment by z-vr** [comment]
I get the same error
```
[10:43:29] 'lint' errored after 3.05 s
[10:43:29] ESLintError in plugin 'gulp-eslint'
Message:
    Unnecessary { after 'for-of'.
Details:
    fileName: test/forms_test.js
    lineNumber: 1431
[10:43:30] 
test/jquery_compat_test.js
  17:3  error  Unnecessary { after 'for-of'  curly
```

**Comment by vcarel** [comment]
So... Can we get this pull-request merged anyway? I think those linting issues should be fixed on the master branch independently.

**Comment by sintanial** [comment]
why jsdom 6.5.1, when recently version is 7.2.0 ?

**Comment by z-vr** [comment]
@sintanial if you look at commits it's up to 7.0.2

**Comment by sintanial** [comment]
@z-vr oO sorry, is was blind :)

**Comment by sintanial** [comment]
@z-vr already is not the last version :)

**Comment by vcarel** [comment]
It shouldn't be 7.0.2... it's not working yet ! I thought I based my PR on my 6.5.1.
I'll look at that when I'll be back to my office,  tomorrow.

So, why 6.5.1 only? Because the 7 branch rehauled the XmlHttpRequest implementation which is patched by zombie. And I need @assaf (or any one) help to continue upgrading jsdom. However the 6.5.1 already brings interresting changes compared to the current version.

**Comment by vcarel** [comment]
If you feel to fix things broken jsdom 7.0.2, don't hesitate to fork my repo ;-) jsdom 7.x is really interesting. I would definitely appreciate to get this version!

**Comment by sintanial** [comment]
@vcarel unfortunately i don't know jsdom, and never hear of it until today :)

**Comment by vcarel** [comment]
I didn't know zombie before. It's never too late and I'll be grateful
forever ;-)

**Comment by sintanial** [comment]
@vcarel research in progress ;)

**Comment by vcarel** [comment]
All right, I issued a new PR so to not include the commits related to 7.0.2 ->  #990

**Pull request closed without merging**
