### PR TITLE
801 event target dataset

### PR DESCRIPTION
**Pull request by StefanoDeVuono**
I've integrated a new version of jsdom into zombie, allowing for dataset attributes to be queried.

There were/are a lot of changes. Please take a look and let me know what you think.

### CODE REVIEW

**Comment by assaf** [comment]
When I run this on my machine (Node 0.9.8) I get two errors:

```
1) Scripts
       file:// uri scheme
         should run scripts with file url src:

      AssertionError [ERR_ASSERTION]: 'JS should change me' deepEqual 'file://'
      + expected - actual

      -JS should change me
      +file://

      at assertMatch (src/assert.js:16:12)
      at Assert.text (src/assert.js:204:5)
      at Context.<anonymous> (test/script_test.js:445:22)

  2) Scripts
       file:// uri with encoded spaces
         should run scripts with file url src containing encoded spaces:

      AssertionError [ERR_ASSERTION]: 'JS should change me' deepEqual 'file://'
      + expected - actual

      -JS should change me
      +file://

      at assertMatch (src/assert.js:16:12)
      at Assert.text (src/assert.js:204:5)
      at Context.<anonymous> (test/script_test.js:456:22)
```

Also, `mocha` doesn't exit

**Comment by assaf** [comment]
I closed this by mistake, please ignore. This update of JSDOM requires Node 8 or later, so I updated the minimum requirement, which also means bumping major version to 6.0. Tests pass successfully on Travis CI under Node 9.8.0, but not on my machine, only these two file: tests fail, and sometimes only one of these tests fail.

**Comment by TerjeBr** [comment]
Thank you @StefanoDeVuono for you great effort. I hope this will make it into a tagged version of zombie soon, because the old jsDom used by zombie does not have the Option constructor.

**Comment by StefanoDeVuono** [comment]
@assaf Thank you so much for your help resolving some issues! I'll take a look at failing tests.
@TerjeBr Thank you for keeping this effort alive!

**Comment by StefanoDeVuono** [comment]
I dug in a little bit and from what I can tell there are is a problem between `return browser.visit(...` in the tests and `response._consume()` in `resourceLoader.load`.

The `browser.visit` function has a wait call which sometimes. The `_consume` function (from ln 287 of fetch.js) returns a promise with an `data` and `end` events on the incoming data stream (the js file in script.src in this case).

Apparently, `browser.visit` sometimes finishes before the `end` event gets handled (which is, in turn, supposed to `_eval` the javascript and mutate the DOM for the purpose of this test). As such the tests fail.

I'm not quite sure why yet. If anyone has any insight, it'd be much appreciated. I'll keep checking it out though.

**Comment by TerjeBr** [comment]
I just know that the browser.visit function calls `this.tabs.open({ url: url, referrer: this.referrer });` before it waits for events to end (or returns a promise for events to end.)

Has anything changed in the `Tabs` object?

**Comment by StefanoDeVuono** [comment]
@TerjeBr Got it. The `jsdomQueue` referenced in `eventloop.js` was in the `document-impl` not the `document`.

@assaf Lemme know if you still get errors or if you see any other snags.

**Comment by assaf** [comment]
👍

**Comment by assaf** [comment]
Just published 6.0 with all these changes! Thank you Stefano

**Comment by vladgurgov** [comment]
Thank you @StefanoDeVuono and @assaf! This is great and long-awaited update!! 
I have few other smaller fixes that i will release in a few weeks once i have a few mins!

**Comment by vladgurgov** [comment]
@StefanoDeVuono @assaf - are you planning on uprading jsdom to 11.12.0 (latest) at anytime? 
I spend some time looking into it today since 11.5.1 that you used at the time seems to miss some critical fixes, which (of course - lucky me!) I bumped into production env.  

I run into some issues while upgrading 11.5.1 -> 11.12.0, will try looking into it again sometime, but any help would be much appreciated!

**Comment by StefanoDeVuono** [comment]
@vladgurgov 

Thanks for the note. If you put out a fork, I'll see if I can contribute, but I'm stretched a little thin rn

**Comment by vladgurgov** [comment]
@StefanoDeVuono no worries! 

I already figured it out and updated to jsdom 11.12.0! @assaf already approved pushed it. so latest zombie master is running on jsdom 11.12.0 already! 
lemme know if you need any help, i might find some time to contribute!

**Pull request merged**
