### PR TITLE
Bump version of ws module

### PR DESCRIPTION
**Pull request by jbergknoff**
This PR address #1017, allowing Zombie to be installed without any compile step. No tests break as a result of the upgrade.

### CODE REVIEW

**Comment by dresende** [comment]
Security problems with current `ws` version.

- https://nodesecurity.io/advisories/120
- https://nodesecurity.io/advisories/67

**Comment by mdlavin** [comment]
I also noticed that there are some issues with ws 0.8 on node 6.x and there are partial fixed in ws 1.x now.  The full conversation is here: https://github.com/websockets/ws/issues/778.

@assaf Is there any way I can help get this merged into zombie?

**Comment by assaf** [comment]
Fork it. If the fork gets a bunch of updates then it would be interesting to merge it back into master and add you as committer on the mainline.

**Comment by jbergknoff** [comment]
@assaf can you clarify your response? Are you saying that the zombie project is abandoned?

It's sort of puzzling if a one-line PR providing obvious and immediate value is less welcome than a major fork with many updates.

**Comment by assaf** [comment]
@jbergknoff if you want to help, there's a bunch of PRs that need attention, get involved, do something, and if it's helping users, than you'll be given access to master.

Clearer?

**Comment by mdlavin** [comment]
For anybody who gets here looking for node v6 compatibility. I've started a branch https://github.com/mdlavin/zombie/tree/node-v6-support that I'll be working on.

**Comment by mdlavin** [comment]
When this merges, it would be a good idea to merge PR #1074 at the same time to avoid breaking existing socket.io clients.

**Pull request merged**
