### PR TITLE
Jsdom 6.5.1 branch

### PR DESCRIPTION
**Pull request by vcarel**
This is a new attempt to upgrade of jsdom from 5.3.0 to 6.5.1, related to the issue #939.
This replace the previous pull request #982 which was including too many commits.

It brings 1 breaking change:

Element.setAttribute now expects two arguments, even for setting properties (such as "checked", "disabled"...): https://developer.mozilla.org/fr/docs/Web/API/Element/setAttribute

### CODE REVIEW

**Comment by sintanial** [comment]
Mmm what's next ? When this PR approved ? It's very important PR, which can fix many bug's with evaluate javascript on different site !

**Comment by assaf** [comment]
@sintanial I'll merge this PR when I get the time to look at it.

**Comment by sintanial** [comment]
@assaf ok, thx ;)

**Comment by vcarel** [comment]
Happy new year everyone :-)
@assaf, I don't want to push you... I hope you will have some time to look at this PR very soon. I really need it.

**Comment by sintanial** [comment]
+1 I look forward to @assaf merge this pull

**Comment by vcarel** [comment]
@assaf... can we get this one merged, please ?

**Comment by sintanial** [comment]
+1 can't wait this merge :)

**Comment by vcarel** [comment]
Just updated the branch so to resolve conflicts.

**Comment by eagleeye** [comment]
meanwhile jsdom got version `8.0.2`...

**Comment by sintanial** [comment]
perhaps the author forgot the repository? 91 issues and 16 pull requests :(

**Comment by eagleeye** [comment]
probably we need to choose fork with new pubic npm, @vcarel as far I can see you have the best fork. How about publishing zombie2 to npm?

**Comment by vcarel** [comment]
Looks like. Any one interested by a fork / revamp based on a fresh version
of JSDom?
And any company who would like to sponsor the work? :-)

2016-02-10 10:19 GMT+01:00 Roman <notifications@github.com>:

**Comment by sintanial** [comment]
I very interested by fork with fresh jsdom, and solved issues :). But unfortunately i not have company which sponsor your work :(

**Comment by sintanial** [comment]
@vcarel hi, i merged your pull request into my fork and tested it, and i found some interesting behaviour.
for example 
```javascript
const Browser = require("./lib");

var browser = new Browser();
browser.waitDuration = 10000;
browser.visit("http://yandex.ru")
    .then(()=> {
        return browser.wait();
    })
    .then(()=> {
        console.log(browser.window.document.title);
    });
```
when i run this code like this ```DEBUG=zombie node test.js```, then in console i received many messages like this: 
```
  zombie Fired setTimeout after 50ms delay +54ms
  zombie Fired setTimeout after 50ms delay +56ms
  zombie Fired setTimeout after 50ms delay +56ms
  zombie Fired setTimeout after 50ms delay +54ms
  zombie Fired setTimeout after 50ms delay +52ms
  zombie Fired setTimeout after 50ms delay +53ms
  zombie Fired setTimeout after 50ms delay +56ms
  zombie Fired setTimeout after 50ms delay +55ms
  zombie Fired setTimeout after 50ms delay +54ms
  zombie Fired setInterval every 1000ms +16ms
  zombie Fired setTimeout after 50ms delay +38ms
  zombie Fired setTimeout after 50ms delay +53ms
  zombie Fired setTimeout after 50ms delay +56ms
  zombie Fired setTimeout after 50ms delay +53ms
```
on original zombie version work fine, but failed with javascript error :(

**Comment by vcarel** [comment]
Hi @sintanial,

I couldn't reproduce your issue. What do you have in your fork?
To get the Browser class, I have to import the zombie module, i.e.:

    const Browser = require('zombie');

Doing so, I'm getting the following error:

    Unhandled rejection TypeError: Cannot read property '0' of null
        at https://yastatic.net/www/2.678/white/pages/bender/_bender.ru.js:8:20039
        in https://www.yandex.ru/

... which is a fault related some Yandex script. If I'm doing the same with google.com, it works (I get `Google`).

FYI, the script I used is:

    const Browser = require('zombie');

    var browser = new Browser();
    browser.waitDuration = 10000;
    browser.visit('http://google.com')
        .then(()=> {
            return browser.wait();
        })
        .then(()=> {
            console.log(browser.window.document.title);
        });

**Comment by sintanial** [comment]
Before reproduce this issue, you need solve error
```
Unhandled rejection TypeError: Cannot read property '0' of null
    at https://yastatic.net/www/2.678/white/pages/bender/_bender.ru.js:8:20039
    in https://www.yandex.ru/
```
this error throwed because zombie and jsdom have't property document.domain
please add this code
```
Object.defineProperty(document, "domain", {
    value: window.location.host,
    writable: false,
    enumerable: true,
  });
```
into this line  https://github.com/vcarel/zombie/blob/jsdom_6.5.1_branch/src/document.js#L474
and try again ;)

**Comment by vcarel** [comment]
@sintanial I added the code (+ a console.log) and now I get:
```
createDocument: added document.domain with value yandex.ru
createDocument: added document.domain with value www.yandex.ru
createDocument: added document.domain with value yastatic.net
createDocument: added document.domain with value yastatic.net
createDocument: added document.domain with value yastatic.net
Яндекс
```

This is still not the same issue. But please note that zombie hang after displaying the title.

**Comment by sintanial** [comment]
hmm, you run script with DEBUG=zombie ?

**Comment by vcarel** [comment]
My bad, I forgot the DEBUG. So now I'm getting your setTimeouts:

 ```
[...]
zombie GET https://yastatic.net/morda-logo/i/ga-counter/7/index.html => 200 +1ms
zombie GET https://yastatic.net/morda-logo/i/ga-counter/7/index.html => 200 +1ms
zombie Loaded document https://yastatic.net/morda-logo/i/ga-counter/7/index.html +6ms
zombie Fired setTimeout after 50ms delay +24ms
zombie Fired setTimeout after 50ms delay +50ms
zombie GET https://www.googleadservices.com/pagead/conversion_async.js => 200 +27ms
zombie Fired setTimeout after 50ms delay +50ms
[...]
 zombie Fired setTimeout after 50ms delay +51ms
Яндекс
```

**Comment by sintanial** [comment]
@vcarel in original zombie, this timeouts not showed\called :)
by the way, i am tried to update from 6.5.1 to 7.0.0, main problem is xhr ?

**Comment by vcarel** [comment]
Well, the `Fired setTimeout` log is written by zombie (in index.js):

      .on('setTimeout', (fn, delay)=> {
        this._debug('Fired setTimeout after %dms delay', delay);
        this.emit('setTimeout', fn, delay);
      })

To get the involved function, I added it to the log:

      .on('setTimeout', (fn, delay)=> {
        this._debug('Fired setTimeout after %dms delay', delay, fn);
        this.emit('setTimeout', fn, delay);
      })

... and I got the following result:

    zombie Fired setTimeout after 50ms delay +50ms function (){r._tick()}
    zombie Fired setTimeout after 50ms delay +50ms function (){r._tick()}
    zombie Fired setTimeout after 50ms delay +50ms function (){r._tick()}

This looks to correspond to the script yastatic.net/www/2.678/white/pages/bender/_bender.ru.js where there's an instruction:

```
setTimeout(function(){r._tick()},s)}
```

I believe that by fixing jsdom, some yandex script could go further and now fail at this point. But I wouldn't blame zombie at the first time. I thing you'll have to get deeper into this code to understand what happens.

**Comment by vcarel** [comment]
Yes, I couldn't upgrade to 7.x because of xhr and cookies. :-(

**Comment by vcarel** [comment]
Hi @assaf, any news ?

**Comment by divmgl** [comment]
@assaf is zombie.js abandoned? You may want to look into finding contributors to help maintain this project.

**Comment by megalithic** [comment]
agreed, i hope that @assaf is ok and able to hand this project off to contribs.

**Comment by mdlavin** [comment]
assaf recently granted me permission to merge and publish versions. I'll try to read through the existing comments here and understand the state of this PR. I'm happy to upgrade jsdom if there aren't any incompatible changes.

**Comment by vcarel** [comment]
Hi Matt,
Thanks for looking into this. If you can find a way to upgrade jsdom to the most recent version, it would be even better (I was blocked at 7.xx, which is already old now)

**Comment by mdlavin** [comment]
I merged these changes and I did an adoption of jsdom 7.x. Is anybody interested in this enough to test the version in master to check for some regressions?  The travis builds are still green, and I'll bump the major version to 5.x to avoid surprises, but more testing is always good.

**Comment by mdlavin** [comment]
I published a new version of zombie, 5.0.0, with the jsdom 7.x adoption. I chose to upgrade the major version of zombie because there were so many changes in the jsdom dependency.

**Pull request merged**
